import { Product, Category, BlogPost, Review, JobPosting, Order } from "./types";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "gastro-care",
    name: "Gastro & Reflux Care",
    slug: "gastro-care",
    productCount: 2,
    sort: 1,
    isActive: true,
    description: "Rapid acid fight therapy antacids and gastro-resistant enteric formulations",
    image: {
      publicId: "cat-gastro-care",
      url: "/images/products/ebl-raft-3d.jpg",
    },
  },
  {
    id: "cardio-care",
    name: "Cardio & Hypertension Care",
    slug: "cardio-care",
    productCount: 3,
    sort: 2,
    isActive: true,
    description: "Cilnidipine IP dual calcium channel blockers for 24hr blood pressure management",
    image: {
      publicId: "cat-cardio-care",
      url: "/images/products/ebl-cilalong-3d.jpg",
    },
  },
  {
    id: "womens-wellness",
    name: "Women's Wellness & Supplements",
    slug: "womens-wellness",
    productCount: 1,
    sort: 3,
    isActive: true,
    description: "Daily multivitamin, essential minerals, iron, and vitality formulas",
    image: {
      publicId: "cat-womens-wellness",
      url: "/images/products/ebl-vitaplus-3d.jpg",
    },
  },
  {
    id: "general-wellness",
    name: "General Health & Immunity",
    slug: "general-wellness",
    productCount: 6,
    sort: 4,
    isActive: true,
    description: "High quality WHO-GMP certified pharmaceutical remedies for the entire family",
    image: {
      publicId: "cat-general-wellness",
      url: "/images/products/ebl-pantop-3d.jpg",
    },
  },
  {
    id: "ultra-thin-condoms",
    name: "Ultra Thin & Natural Feel",
    slug: "ultra-thin-condoms",
    productCount: 1,
    sort: 5,
    isActive: true,
    description: "0.03mm ultra-sensitive natural feel latex with buttercup seal",
    image: {
      publicId: "cat-ultrathin",
      url: "/images/products/ebl-ultrathin-3d.jpg",
    },
  },
  {
    id: "climax-delay-condoms",
    name: "Climax Delay & Endurance",
    slug: "climax-delay-condoms",
    productCount: 1,
    sort: 6,
    isActive: true,
    description: "Benzocaine active formulation designed for prolonged endurance",
    image: {
      publicId: "cat-endurance",
      url: "/images/products/ebl-endurance-3d.jpg",
    },
  },
  {
    id: "lubricants",
    name: "Lubricants & Intimate Gels",
    slug: "lubricants",
    productCount: 1,
    sort: 7,
    isActive: true,
    description: "Water-based hydrating lubrication for enhanced comfort and glide",
    image: {
      publicId: "cat-lubricants",
      url: "/images/products/ebl-lube-3d.jpg",
    },
  },
  {
    id: "personal-massagers",
    name: "Personal Massagers",
    slug: "personal-massagers",
    productCount: 1,
    sort: 8,
    isActive: true,
    description: "Body-safe silicone multi-speed personal wellness massagers and rings",
    image: {
      publicId: "cat-massagers",
      url: "/images/products/ebl-massager-3d.jpg",
    },
  },
  {
    id: "extra-dotted-condoms",
    name: "Extra Dotted & Ribbed",
    slug: "extra-dotted-condoms",
    productCount: 1,
    sort: 9,
    isActive: true,
    description: "Pyramid dotted matrices and contour ribbing for elevated pleasure",
    image: {
      publicId: "cat-dotted",
      url: "/images/products/ebl-matrix-3d.jpg",
    },
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "eb-prod-001",
    sku: "EBL-RAFT-200ML",
    name: "EBL RAFT Rapid Acid Fight Therapy Antacid Suspension (200 ml)",
    slug: "ebl-raft-rapid-acid-fight-therapy-antacid-suspension-200ml",
    categoryId: "gastro-care",
    categoryName: "Gastro Care",
    brandName: "EBL Pharmaceuticals",
    shortDesc: "Fast-acting foaming raft barrier and acid neutralization suspension for instant relief from GERD and heartburn.",
    description: "EBL RAFT Rapid Acid Fight Therapy Suspension (200 ml) is an advanced gastric mucosal shield formulated by Eastern Biochemicals. It combines fast acid neutralization with an active raft-forming matrix that floats on top of stomach contents, physically blocking acid regurgitation into the esophagus. Refreshing cooling mint flavor, non-chalky, and gentle on digestion.",
    howToUse: "Shake bottle well before use. Adults and children 12 years and over: Take 10 to 20 ml (2 to 4 measuring spoonfuls) after meals and at bedtime, or as recommended by your physician.",
    specs: {
      Volume: "200 ml",
      Formulation: "Oral Liquid Suspension",
      Flavour: "Refreshing Cooling Mint",
      Indication: "Heartburn, Acid Reflux, GERD, Gastric Discomfort",
      Storage: "Store below 30°C in a dry place. Protect from direct sunlight.",
    },
    mrpPaise: 21000,
    pricePaise: 16500,
    gstRate: 12,
    hsnCode: "30049099",
    unit: "Bottle (200ml)",
    weightG: 240,
    trackInventory: true,
    reorderLevel: 25,
    maxLevel: 200,
    stockAvailable: 150,
    isLowStock: false,
    requiresPrescription: false,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-raft-1",
        url: "/images/products/ebl-raft-3d.jpg",
        alt: "EBL RAFT Rapid Acid Fight Therapy Antacid Suspension 200ml",
        sort: 1,
        isPrimary: true,
      },
      {
        publicId: "prod-raft-2",
        url: "/images/products/ebl-raft-bottle.jpg",
        alt: "EBL RAFT Suspension Medicine Bottle",
        sort: 2,
      },
      {
        publicId: "prod-raft-3",
        url: "/images/products/ebl-raft-box.jpg",
        alt: "EBL RAFT Outer Packaging Retail Carton",
        sort: 3,
      },
      {
        publicId: "prod-raft-4",
        url: "/images/products/ebl-banner-raft.jpg",
        alt: "EBL RAFT Clinical Presentation",
        sort: 4,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["ebl", "raft", "antacid", "suspension", "acidity", "heartburn", "gerd", "reflux"],
    ratingAvg: 4.9,
    ratingCount: 48,
    seoTitle: "EBL RAFT Rapid Acid Fight Therapy Antacid Suspension 200ml | EBL Store",
    seoDesc: "Buy EBL RAFT 200ml Antacid Suspension online. Rapid foaming raft barrier relieves acid reflux and heartburn fast.",
    createdAt: "2026-08-10T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "eb-prod-002",
    sku: "EBL-CILA-10MG",
    name: "EBL Cilalong 10 mg Cilnidipine Tablets IP (3 x 10 Tablets)",
    slug: "ebl-cilalong-10mg-cilnidipine-tablets-ip",
    categoryId: "cardio-care",
    categoryName: "Cardiovascular Care",
    brandName: "EBL Pharmaceuticals",
    shortDesc: "Dual L/N-type calcium channel blocker for smooth 24-hour blood pressure regulation and cardio-renal protection.",
    description: "EBL Cilalong 10 mg contains pharmaceutical grade Cilnidipine IP, a breakthrough fourth-generation calcium channel blocker. Unlike conventional CCBs, Cilalong acts on both L-type and N-type calcium channels, suppressing sympathetic nervous activity and dramatically minimizing pedal edema and reflex tachycardia.",
    howToUse: "As prescribed by a registered medical practitioner. Usually one tablet once daily after breakfast or dinner with water.",
    specs: {
      Composition: "Cilnidipine IP 10 mg",
      Packaging: "3 Blister Strips of 10 Tablets (30 Tablets Total)",
      Form: "Oral Film-Coated Tablets",
      Storage: "Store in a cool, dry place away from light and moisture.",
    },
    mrpPaise: 31000,
    pricePaise: 24000,
    gstRate: 12,
    hsnCode: "30049099",
    unit: "Pack of 30 Tablets",
    weightG: 50,
    trackInventory: true,
    reorderLevel: 40,
    maxLevel: 300,
    stockAvailable: 280,
    isLowStock: false,
    requiresPrescription: true,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-cilalong-10-1",
        url: "/images/products/ebl-cilalong-3d.jpg",
        alt: "EBL Cilalong 10 mg Cilnidipine Tablets IP",
        sort: 1,
        isPrimary: true,
      },
      {
        publicId: "prod-cilalong-10-2",
        url: "/images/products/ebl-cilalong.jpg",
        alt: "EBL Cilalong Range Clinical Display",
        sort: 2,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["cilalong", "cilnidipine", "10mg", "hypertension", "blood pressure", "ebl", "cardio"],
    ratingAvg: 4.85,
    ratingCount: 36,
    seoTitle: "EBL Cilalong 10 mg Cilnidipine Tablets IP | EBL Store",
    seoDesc: "Buy EBL Cilalong 10mg Cilnidipine Tablets online. Dual L/N-type CCB for 24-hour hypertension management.",
    createdAt: "2026-08-12T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "eb-prod-003",
    sku: "EBL-CILA-5MG",
    name: "EBL Cilalong 5 mg Cilnidipine Tablets IP (3 x 10 Tablets)",
    slug: "ebl-cilalong-5mg-cilnidipine-tablets-ip",
    categoryId: "cardio-care",
    categoryName: "Cardiovascular Care",
    brandName: "EBL Pharmaceuticals",
    shortDesc: "Starter dosage formulation for gentle blood pressure titration and essential hypertension control.",
    description: "EBL Cilalong 5 mg provides optimal starting dosage for newly diagnosed hypertensive patients, allowing gentle hemodynamic stabilization with minimal side effects.",
    howToUse: "Take exactly as directed by your cardiologist or healthcare provider.",
    specs: {
      Composition: "Cilnidipine IP 5 mg",
      Packaging: "3 Blister Strips of 10 Tablets (30 Tablets Total)",
      Form: "Oral Film-Coated Tablets",
    },
    mrpPaise: 21000,
    pricePaise: 16000,
    gstRate: 12,
    hsnCode: "30049099",
    unit: "Pack of 30 Tablets",
    weightG: 50,
    trackInventory: true,
    reorderLevel: 30,
    maxLevel: 250,
    stockAvailable: 220,
    isLowStock: false,
    requiresPrescription: true,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-cilalong-5-1",
        url: "/images/products/ebl-cilalong-3d.jpg",
        alt: "EBL Cilalong 5 mg Cilnidipine Tablets IP",
        sort: 1,
        isPrimary: true,
      },
      {
        publicId: "prod-cilalong-5-2",
        url: "/images/products/ebl-cilalong.jpg",
        alt: "EBL Cilalong Packaging Collection",
        sort: 2,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["cilalong", "cilnidipine", "5mg", "hypertension", "ebl"],
    ratingAvg: 4.8,
    ratingCount: 22,
    createdAt: "2026-08-15T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "eb-prod-004",
    sku: "EBL-CILA-20MG",
    name: "EBL Cilalong 20 mg Cilnidipine Tablets IP (3 x 10 Tablets)",
    slug: "ebl-cilalong-20mg-cilnidipine-tablets-ip",
    categoryId: "cardio-care",
    categoryName: "Cardiovascular Care",
    brandName: "EBL Pharmaceuticals",
    shortDesc: "High potency formulation for resistant hypertension and renal protective therapy.",
    description: "EBL Cilalong 20 mg delivers intensive 24-hour arterial pressure lowering with pronounced renal microcirculation preservation and albuminuria reduction.",
    howToUse: "Strictly as instructed by a qualified medical practitioner.",
    specs: {
      Composition: "Cilnidipine IP 20 mg",
      Packaging: "3 Blister Strips of 10 Tablets (30 Tablets Total)",
      Form: "Oral Film-Coated Tablets",
    },
    mrpPaise: 49500,
    pricePaise: 39000,
    gstRate: 12,
    hsnCode: "30049099",
    unit: "Pack of 30 Tablets",
    weightG: 50,
    trackInventory: true,
    reorderLevel: 25,
    maxLevel: 200,
    stockAvailable: 140,
    isLowStock: false,
    requiresPrescription: true,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-cilalong-20-1",
        url: "/images/products/ebl-cilalong-3d.jpg",
        alt: "EBL Cilalong 20 mg Cilnidipine Tablets IP",
        sort: 1,
        isPrimary: true,
      },
      {
        publicId: "prod-cilalong-20-2",
        url: "/images/products/ebl-cilalong.jpg",
        alt: "EBL Cilalong Overview",
        sort: 2,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["cilalong", "cilnidipine", "20mg", "hypertension", "ebl"],
    ratingAvg: 4.9,
    ratingCount: 19,
    createdAt: "2026-08-18T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "eb-prod-005",
    sku: "EBL-PANTOP-DSR",
    name: "EBL Pantop-DSR Gastro Resistant Capsules (10 x 10 Capsules)",
    slug: "ebl-pantop-dsr-gastro-resistant-capsules",
    categoryId: "gastro-care",
    categoryName: "Gastro Care",
    brandName: "EBL Pharmaceuticals",
    shortDesc: "Pantoprazole 40mg + Domperidone 30mg SR for chronic GERD, gastric ulcer healing, and anti-emetic motility.",
    description: "EBL Pantop-DSR combines enteric coated Pantoprazole pellets to suppress excessive acid output with sustained release Domperidone pellets to restore normal upper GI transit and eliminate nauseous morning acid reflux.",
    howToUse: "Take one capsule once daily in the morning, 30 to 60 minutes before breakfast with a glass of water.",
    specs: {
      Composition: "Pantoprazole Sodium IP eq. to Pantoprazole 40mg + Domperidone IP 30mg (as Sustained Release)",
      Packaging: "10 Strips of 10 Capsules (100 Capsules Box)",
      Form: "Hard Gelatin Capsules containing Enteric & SR Pellets",
    },
    mrpPaise: 24500,
    pricePaise: 18500,
    gstRate: 12,
    hsnCode: "30049099",
    unit: "Box of 100 Capsules",
    weightG: 95,
    trackInventory: true,
    reorderLevel: 25,
    maxLevel: 250,
    stockAvailable: 190,
    isLowStock: false,
    requiresPrescription: true,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-pantop-1",
        url: "/images/products/ebl-pantop-3d.jpg",
        alt: "EBL Pantop-DSR Gastro Resistant Capsules",
        sort: 1,
        isPrimary: true,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["pantop", "dsr", "pantoprazole", "domperidone", "gerd", "acidity", "ebl"],
    ratingAvg: 4.88,
    ratingCount: 42,
    createdAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "eb-prod-006",
    sku: "EBL-VITAPLUS-W",
    name: "EBL VitaPlus Women Daily Multivitamin & Minerals (100 Tablets)",
    slug: "ebl-vitaplus-women-daily-multivitamin-minerals",
    categoryId: "womens-wellness",
    categoryName: "Women's Wellness",
    brandName: "EBL Pharmaceuticals",
    shortDesc: "Essential daily nutrition formulated with Iron, Calcium, Vitamin D3, Folic Acid, and antioxidant complex for active women.",
    description: "EBL VitaPlus Women is a premium high-potency daily micronutrient supplement designed to support female hormonal balance, bone density, high energy stamina, cellular renewal, and radiant skin and hair.",
    howToUse: "Take 1 tablet daily with or immediately after a main meal, or as advised by your nutritionist.",
    specs: {
      Composition: "24 Essential Vitamins, Minerals, and Bioactive Botanicals",
      Packaging: "Amber Bottle of 100 Coated Tablets",
      Form: "Coated Tablets",
    },
    mrpPaise: 69900,
    pricePaise: 49900,
    gstRate: 18,
    hsnCode: "21069099",
    unit: "Bottle of 100 Tablets",
    weightG: 180,
    trackInventory: true,
    reorderLevel: 20,
    maxLevel: 200,
    stockAvailable: 130,
    isLowStock: false,
    requiresPrescription: false,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-vitaplus-1",
        url: "/images/products/ebl-vitaplus-3d.jpg",
        alt: "EBL VitaPlus Women Daily Multivitamin & Minerals",
        sort: 1,
        isPrimary: true,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["vitaplus", "women", "multivitamin", "supplements", "vitality", "iron", "calcium"],
    ratingAvg: 4.92,
    ratingCount: 54,
    createdAt: "2026-08-22T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "eb-prod-007",
    sku: "EBL-LUBE-100ML",
    name: "EBL Pure Silk Intimate Hydrating Lubricant & Gel (100 ml)",
    slug: "ebl-pure-silk-intimate-hydrating-lubricant-100ml",
    categoryId: "lubricants",
    categoryName: "Lubricants & Gels",
    brandName: "EBL Care",
    shortDesc: "Silky, pH-balanced water-based hydrating formula for effortless comfort and gentle glide.",
    description: "EBL Pure Silk is a body-safe, ultra-pure water-based intimate lubricant engineered by Eastern Biochemicals. Non-staining, dermatologically tested, and free from parabens or harsh petrochemicals.",
    howToUse: "Dispense 2 to 3 pumps onto fingertips and apply gently to intimate areas as desired. Reapply as needed.",
    specs: {
      Volume: "100 ml",
      Base: "Pure Water-Based",
      pH: "Balanced 4.5 - 5.5",
      Features: "Paraben Free, Condom Safe, Easy Wash",
    },
    mrpPaise: 49900,
    pricePaise: 39900,
    gstRate: 18,
    hsnCode: "33079090",
    unit: "Pump Bottle (100ml)",
    weightG: 140,
    trackInventory: true,
    reorderLevel: 25,
    maxLevel: 200,
    stockAvailable: 160,
    isLowStock: false,
    requiresPrescription: false,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-lube-1",
        url: "/images/products/ebl-lube-3d.jpg",
        alt: "EBL Pure Silk Intimate Hydrating Lubricant 100ml",
        sort: 1,
        isPrimary: true,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["lube", "lubricant", "ebl", "intimate", "water based", "silk"],
    ratingAvg: 4.9,
    ratingCount: 38,
    createdAt: "2026-08-25T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "eb-prod-008",
    sku: "EBL-PULSE-RING",
    name: "EBL Pulse Ergonomic Body-Safe Wellness Massager Device (1 pc)",
    slug: "ebl-pulse-ergonomic-body-safe-wellness-massager",
    categoryId: "personal-massagers",
    categoryName: "Personal Massagers",
    brandName: "EBL Care",
    shortDesc: "Whisper-quiet, 10-speed medical-grade silicone vibrating massager and ring for couple wellness.",
    description: "Crafted with 100% body-safe velvety medical silicone, EBL Pulse features a precision micro-motor delivering powerful yet whisper-quiet harmonic vibrations. Fully waterproof with ergonomic contours.",
    howToUse: "Wash before and after use with mild soap and warm water. Activate single-button control to cycle through 10 vibration frequencies.",
    specs: {
      Material: "Medical-Grade Velvet Silicone",
      Speeds: "10 Harmonic Frequencies",
      Waterproof: "IPX7 Submersible",
      Power: "Body-safe button cell battery included",
    },
    mrpPaise: 79900,
    pricePaise: 54900,
    gstRate: 18,
    hsnCode: "90191020",
    unit: "1 Device",
    weightG: 65,
    trackInventory: true,
    reorderLevel: 20,
    maxLevel: 150,
    stockAvailable: 95,
    isLowStock: false,
    requiresPrescription: false,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-massager-1",
        url: "/images/products/ebl-massager-3d.jpg",
        alt: "EBL Pulse Ergonomic Body-Safe Wellness Massager",
        sort: 1,
        isPrimary: true,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["pulse", "massager", "ebl", "vibrating ring", "wellness", "silicone"],
    ratingAvg: 4.86,
    ratingCount: 29,
    createdAt: "2026-08-28T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "eb-prod-009",
    sku: "EBL-THINX-10S",
    name: "EBL Feather-Touch 0.03 mm Ultra-Thin Condoms (10 pcs)",
    slug: "ebl-feather-touch-003mm-ultra-thin-condoms",
    categoryId: "ultra-thin-condoms",
    categoryName: "Ultra Thin Condoms",
    brandName: "EBL Care",
    shortDesc: "Micro-engineered 0.03 mm premium natural latex with buttercup peel packaging for skin-to-skin touch.",
    description: "EBL Feather-Touch sets a new standard for natural intimacy. Measuring a remarkable 0.03 mm, each unit is electronically tested for supreme tensile resilience, offering unhindered heat transfer and sensitivity.",
    howToUse: "Peel open individual hermetic buttercup seal from the curved tab. Apply onto erect anatomy before contact.",
    specs: {
      Thickness: "0.03 mm Ultra-Thin",
      Material: "Pure Premium Natural Rubber Latex",
      Lubrication: "Extra Silky Silicone Reservoir",
      Packaging: "Easy-Peel Hermetic Buttercup 10-Pack",
    },
    mrpPaise: 39900,
    pricePaise: 29900,
    gstRate: 12,
    hsnCode: "40141000",
    unit: "Box of 10 Condoms",
    weightG: 55,
    trackInventory: true,
    reorderLevel: 30,
    maxLevel: 300,
    stockAvailable: 240,
    isLowStock: false,
    requiresPrescription: false,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-ultrathin-1",
        url: "/images/products/ebl-ultrathin-3d.jpg",
        alt: "EBL Feather-Touch 0.03 mm Ultra-Thin Condoms 10-Pack",
        sort: 1,
        isPrimary: true,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["ultra thin", "feather touch", "0.03mm", "ebl", "condom", "buttercup"],
    ratingAvg: 4.94,
    ratingCount: 67,
    createdAt: "2026-08-30T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "eb-prod-010",
    sku: "EBL-ENDURE-10S",
    name: "EBL Climax Endurance & Delay Protective Essentials (10 pcs)",
    slug: "ebl-climax-endurance-delay-condoms",
    categoryId: "climax-delay-condoms",
    categoryName: "Climax Delay Condoms",
    brandName: "EBL Care",
    shortDesc: "Specially formulated benzocaine delay lubricant for prolonged stamina and synchronized climaxes.",
    description: "EBL Climax Endurance incorporates safe 4.5% benzocaine active inner lubricant to gently desensitize and extend peak endurance while leaving outer partner sensitivity fully heightened.",
    howToUse: "Apply with the delay lubricant positioned on the inside. Suitable for prolonged encounters.",
    specs: {
      ActiveIngredient: "Benzocaine 4.5% Active Delay Formulation",
      Material: "Natural Rubber Latex",
      Packaging: "Box of 10 Units",
    },
    mrpPaise: 44900,
    pricePaise: 34900,
    gstRate: 12,
    hsnCode: "40141000",
    unit: "Box of 10 Condoms",
    weightG: 55,
    trackInventory: true,
    reorderLevel: 25,
    maxLevel: 250,
    stockAvailable: 210,
    isLowStock: false,
    requiresPrescription: false,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-endure-1",
        url: "/images/products/ebl-endurance-3d.jpg",
        alt: "EBL Climax Endurance & Delay Condoms",
        sort: 1,
        isPrimary: true,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["climax delay", "endurance", "ebl", "condom", "long lasting"],
    ratingAvg: 4.88,
    ratingCount: 45,
    createdAt: "2026-09-02T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "eb-prod-011",
    sku: "EBL-MATRIX-10S",
    name: "EBL Matrix Dotted & Ribbed Textured Essentials (10 pcs)",
    slug: "ebl-matrix-dotted-ribbed-condoms",
    categoryId: "extra-dotted-condoms",
    categoryName: "Extra Dotted Condoms",
    brandName: "EBL Care",
    shortDesc: "Pyramid dot matrix and contoured ribbing engineered for elevated tactile pleasure.",
    description: "EBL Matrix delivers intense sensation with over 500 raised pyramid dots and circular ribs strategically positioned along the anatomical shaft.",
    howToUse: "Carefully roll on prior to contact. Electronically verified for absolute safety.",
    specs: {
      Texture: "Raised Pyramid Dots & Circular Ribs",
      Material: "Natural Rubber Latex",
      Packaging: "Box of 10 Units",
    },
    mrpPaise: 39900,
    pricePaise: 29900,
    gstRate: 12,
    hsnCode: "40141000",
    unit: "Box of 10 Condoms",
    weightG: 55,
    trackInventory: true,
    reorderLevel: 25,
    maxLevel: 250,
    stockAvailable: 185,
    isLowStock: false,
    requiresPrescription: false,
    ageRestricted18Plus: false,
    isFeatured: true,
    isTrending: true,
    images: [
      {
        publicId: "prod-matrix-1",
        url: "/images/products/ebl-matrix-3d.jpg",
        alt: "EBL Matrix Dotted & Ribbed Condoms",
        sort: 1,
        isPrimary: true,
      },
    ],
    status: "PUBLISHED",
    searchKeywords: ["matrix", "dotted", "ribbed", "ebl", "texture", "condom"],
    ratingAvg: 4.85,
    ratingCount: 39,
    createdAt: "2026-09-05T10:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
];

export const INITIAL_REVIEWS: Review[] = [];

export const INITIAL_BLOGS: BlogPost[] = [
  {
    id: "blog-001",
    title: "Sexual Pleasure Made Easy with Flavoured Lube",
    slug: "sexual-pleasure-made-easy-with-flavoured-lube",
    excerpt: "Discover how water-soluble gourmet flavours can elevate sensory play and comfort in the bedroom.",
    body: "Intimacy thrives on curiosity and mutual relaxation. When introducing flavoured lubricants into your intimate moments, quality ingredients matter above all. Eastern Biochemicals crafts body-safe, pH-balanced formulas that enhance sensations without irritating delicate tissue...",
    coverUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80",
    category: "Flavoured",
    author: "Dr. Rohini Verma",
    publishedAt: "28 Sep 2026",
    readTime: "4 min read",
  },
  {
    id: "blog-002",
    title: "Vegan Quality Condoms: Are They Truly Safe?",
    slug: "vegan-quality-condoms-are-they-truly-safe",
    excerpt: "Everything you need to know about casein-free latex processing, allergy risks, and barrier reliability.",
    body: "Standard latex manufacturing often utilizes milk protein casein during processing. Vegan-certified condoms by Eastern Biochemicals utilize plant-derived coagulants without compromising on ISO tensile strength and electronic hole testing...",
    coverUrl: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=800&auto=format&fit=crop&q=80",
    category: "Sexual Health",
    author: "Eastern R&D Team",
    publishedAt: "22 Sep 2026",
    readTime: "5 min read",
  },
  {
    id: "blog-003",
    title: "Using Lubes for Intimate Wellness | The EBL Care Guide",
    slug: "using-lubes-for-intimate-wellness-ebl-guide",
    excerpt: "Learn how temperature play, viscosity balance, and proper application unlock deeper connection.",
    body: "Lube is not just a problem solver — it is an intimacy amplifier. Whether pairing with thin latex or textured massagers, understanding water vs silicone bases helps ensure complete safety and lasting comfort...",
    coverUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
    category: "Intimate Care",
    author: "Siddharth Rao",
    publishedAt: "18 Sep 2026",
    readTime: "6 min read",
  },
  {
    id: "blog-004",
    title: "Size Vs. Sexual Stamina - What Matters The Most?",
    slug: "size-vs-sexual-stamina-what-matters-the-most",
    excerpt: "Deconstructing modern intimacy myths with physiological science and emotional bonding facts.",
    body: "Medical studies consistently reveal that psychological presence, foreplay duration, and gentle friction control far outweigh anatomical dimensions. Explore how delay gels and vibrating rings facilitate simultaneous climaxes...",
    coverUrl: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=80",
    category: "Sex Guide",
    author: "Dr. Rohini Verma",
    publishedAt: "12 Sep 2026",
    readTime: "5 min read",
  },
  {
    id: "blog-005",
    title: "5 Everyday Poses From Yoga for Better Sex: For Him",
    slug: "5-everyday-poses-from-yoga-for-better-sex-for-him",
    excerpt: "Strengthen pelvic floor muscles and boost cardiovascular stamina with simple daily stretches.",
    body: "Pelvic floor control through Bridge Pose, Cobra, and Cat-Cow dramatically increases blood circulation and ejaculation control. Pair your daily routine with mindful breathing for profound wellness...",
    coverUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80",
    category: "Wellness & Life",
    author: "Health & Fitness Desk",
    publishedAt: "05 Sep 2026",
    readTime: "7 min read",
  },
  {
    id: "blog-006",
    title: "How to Have the Safest Sex with Ultra-Thin Condoms",
    slug: "how-to-have-the-safest-sex-with-ultra-thin-condoms",
    excerpt: "Why modern 0.03mm polymer latex delivers identical STI and pregnancy protection as thick barriers.",
    body: "Tensile stretch and burst volume tests verify that 0.03mm thickness offers complete protection when applied without trapped air in the reservoir. Learn step-by-step buttercup peel methods...",
    coverUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=800&auto=format&fit=crop&q=80",
    category: "Sexual Health",
    author: "Eastern R&D Team",
    publishedAt: "01 Sep 2026",
    readTime: "4 min read",
  },
];

export const INITIAL_ORDERS: Order[] = [];

export const INITIAL_JOBS: JobPosting[] = [
  {
    id: "job-001",
    title: "Senior Formulation Scientist (Oral & Topical)",
    slug: "senior-formulation-scientist",
    role: "Lead R&D Formulation Chemist",
    department: "R&D & Innovation",
    location: "Guwahati / Agartala, India",
    employmentType: "Full-Time",
    experienceRange: "5-8 Years",
    salaryRange: "₹12,00,000 - ₹18,00,000 PA",
    educationalCriteria: "M.Pharm or Ph.D. in Pharmaceutics / Formulation Science",
    lastDateToApply: "2026-11-30",
    description: "Lead groundbreaking biochemical formulation development for novel generic actives and topical emulsions. Collaborate directly with medical directors and state-of-the-art testing laboratories.",
    requirements: [
      "M.Pharm or Ph.D. in Pharmaceutics / Formulation Science",
      "5+ years proven track record in cGMP compliant sterile or topical manufacturing",
      "Deep expertise in stability testing, ICH guidelines, and dissolution profiling",
      "Experience leading junior analytical chemists and publication track record",
    ],
    benefits: [
      "Industry-leading compensation & annual performance bonus",
      "Comprehensive family health insurance + OPD coverage",
      "Relocation allowance & company accommodation support",
      "Sponsored international conference registrations",
    ],
    status: "OPEN",
    postedAt: "25 Sep 2026",
    openingsCount: 2,
  },
  {
    id: "job-002",
    title: "Quality Assurance & Regulatory Affairs Manager",
    slug: "qa-regulatory-affairs-manager",
    role: "QA Lead & Regulatory Compliance Specialist",
    department: "Quality & Compliance",
    location: "Chennai / Agartala, India",
    employmentType: "Full-Time",
    experienceRange: "6-10 Years",
    salaryRange: "₹14,00,000 - ₹20,00,000 PA",
    educationalCriteria: "B.Pharm / M.Sc. Chemistry / M.Pharm",
    lastDateToApply: "2026-11-25",
    description: "Oversee batch release documentation, CDSCO dossier filings, ISO 45001 / WHO-GMP audit readiness, and vendor quality management.",
    requirements: [
      "B.Pharm / M.Sc. Chemistry with thorough understanding of Drugs & Cosmetics Act",
      "Extensive background in facing statutory drug inspector audits and QA validations",
      "Strong analytical and root-cause analysis (CAPA) problem solving skills",
    ],
    benefits: [
      "Senior leadership growth pathway",
      "Performance incentives & ESOP eligibility",
      "Executive health checkups & wellness benefits",
    ],
    status: "OPEN",
    postedAt: "20 Sep 2026",
    openingsCount: 1,
  },
  {
    id: "job-003",
    title: "Supply Chain & E-Commerce Operations Executive",
    slug: "supply-chain-ecommerce-operations-executive",
    role: "Logistics, Order Fulfillment & Dispatch Coordinator",
    department: "Operations & Logistics",
    location: "Chennai, India",
    employmentType: "Full-Time",
    experienceRange: "2-4 Years",
    salaryRange: "₹5,00,000 - ₹7,50,000 PA",
    educationalCriteria: "Graduate in Logistics, Commerce, or B.Sc",
    lastDateToApply: "2026-11-15",
    description: "Coordinate courier dispatch, AWB tracking, COD reconciliation, and warehouse inventory replenishment across regional distribution nodes.",
    requirements: [
      "Graduate in Logistics, Commerce, or related domain",
      "Hands-on experience with domestic courier APIs (BlueDart, Delhivery) and ERP systems",
      "Proficiency in Excel, inventory ledgers, and customer fulfillment tracking",
    ],
    benefits: [
      "Fast-paced D2C operational experience",
      "Annual appraisal and performance bonuses",
      "Friendly work culture with flexible hours",
    ],
    status: "OPEN",
    postedAt: "28 Sep 2026",
    openingsCount: 3,
  },
];
